-- 1. CONFIGURACIÓN DE USUARIOS
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

BEGIN
    EXECUTE IMMEDIATE 'CREATE USER USUARIOS_ADMIN IDENTIFIED BY AdminPass123$';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO USUARIOS_ADMIN';
    EXECUTE IMMEDIATE 'CREATE USER USUARIOS_APP IDENTIFIED BY AppPass123$';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO USUARIOS_APP';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO USUARIOS_APP';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Si el usuario ya existe, continúa
END;
/

-- 2. ELIMINACIÓN DE TABLAS (En orden inverso de jerarquía)
BEGIN
    FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'USUARIOS_ADMIN' 
              AND table_name IN ('ARTICULO_COMPRA', 'COMPRAS', 'CLIENTES', 'INFORMACION_FISCAL', 'ARTICULOS'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE USUARIOS_ADMIN.' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 3. CREACIÓN DE TABLAS

-- Tabla independiente: Artículos con restricción de nombre único
CREATE TABLE USUARIOS_ADMIN.articulos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    descripcion     CLOB NOT NULL,
    precio_actual   NUMBER(10,2) NOT NULL,
    stock           NUMBER(10) NOT NULL,
    activo          NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT uk_articulo_nombre UNIQUE (nombre) -- Evita duplicar productos
);

-- Tabla PADRE: Información Fiscal con restricción de teléfono único
CREATE TABLE USUARIOS_ADMIN.informacion_fiscal (
    nif_cif           VARCHAR2(20) PRIMARY KEY,
    direccion_fiscal  VARCHAR2(255) NOT NULL,
    telefono          VARCHAR2(20) NOT NULL,
    CONSTRAINT uk_fiscal_telefono UNIQUE (telefono) -- Evita que dos sujetos compartan teléfono
);

-- Tabla HIJA: Clientes
CREATE TABLE USUARIOS_ADMIN.clientes (
    nif_cif         VARCHAR2(20) PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) NOT NULL UNIQUE,
    fecha_registro  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_cliente_fiscal FOREIGN KEY (nif_cif) 
        REFERENCES USUARIOS_ADMIN.informacion_fiscal(nif_cif) 
        ON DELETE CASCADE
);

-- Tabla de Compras
CREATE TABLE USUARIOS_ADMIN.compras (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_realizada   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado            VARCHAR2(20) NOT NULL,
    direccion_envio   VARCHAR2(255),
    precio_total      NUMBER(10,2),
    cliente_nif       VARCHAR2(20) NULL,
    CONSTRAINT fk_compra_cliente FOREIGN KEY (cliente_nif) 
        REFERENCES USUARIOS_ADMIN.clientes(nif_cif) 
        ON DELETE SET NULL
);

-- Tabla de Detalle (Relación N:M)
CREATE TABLE USUARIOS_ADMIN.articulo_compra (
    id_articulo      NUMBER NOT NULL,
    id_compra        NUMBER NOT NULL,
    precio_congelado NUMBER(10,2) NOT NULL,
    unidades         NUMBER(10) NOT NULL,
    CONSTRAINT pk_articulo_compra PRIMARY KEY (id_articulo, id_compra),
    CONSTRAINT fk_ac_articulo FOREIGN KEY (id_articulo) 
        REFERENCES USUARIOS_ADMIN.articulos(id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_compra FOREIGN KEY (id_compra) 
        REFERENCES USUARIOS_ADMIN.compras(id) ON DELETE CASCADE
);

-- 4. TRIGGERS DE SEGURIDAD (Protección contra borrado físico)

CREATE OR REPLACE TRIGGER USUARIOS_ADMIN.TRG_NO_BORRAR_ARTICULOS
BEFORE DELETE ON USUARIOS_ADMIN.articulos
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'SEGURIDAD: No está permitido borrar artículos. Use el borrado lógico (campo activo).');
END;
/

CREATE OR REPLACE TRIGGER USUARIOS_ADMIN.TRG_NO_BORRAR_COMPRAS
BEFORE DELETE ON USUARIOS_ADMIN.compras
BEGIN
    RAISE_APPLICATION_ERROR(-20002, 'SEGURIDAD: Las compras son registros contables permanentes y no se pueden eliminar.');
END;
/

CREATE OR REPLACE TRIGGER USUARIOS_ADMIN.TRG_NO_BORRAR_DETALLES
BEFORE DELETE ON USUARIOS_ADMIN.articulo_compra
BEGIN
    RAISE_APPLICATION_ERROR(-20003, 'SEGURIDAD: No se pueden eliminar líneas de detalle de una compra existente.');
END;
/